### ISSUE TITLE
Return `slotProgress`  and `gasUsed` for `NonceSubmitted` to simplify profitability calculations.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#101]
Adding the `slotProgress` and `gasUsed` to be returned by the `NonceSubmitted` event would simplify the profitability calculation and make it more deterministic.

Current implementation:
 
 1. submit a transaction
 1. The geth client waits for the transaction to complete and records the tx cost.
 1. get `slotProgress` (there could be a race here as other txs could have passed)
 1. Save the transaction cost and the slot number in the db.
 1. on the next transaction check if we have a price for the next slot, If yes then just calculate the profit, and if not leave the transaction to continue.

New implementation:

 1. submit a transaction
 1. The geth client waits for the `NonceSubmitted` to get `gasUsed` and `slotProgress`
 1. Save the transaction cost and the slot number in the db.
 1. on the next transaction check if we have a price for the next slot, If yes then just calculate the profit, and if not leave the transaction to continue.

The only problem is that the miner needs to submit at least one transaction for each slot before it can know its price.

**Comment by krasi-georgiev** [comment]
also, it would help to add a function `currenReward` so that we don't have to duplicate the reward calculation inside the miner. Additionally when the calculation is changed inside the contract wouldn't need to change anything on the miner side.

**Comment by mikeghen** [comment]
I'm not sure this should be done, I'm fairly sure this increases the gas price for all slots. you can just calculate the current reward using the time returned from `tellor.getUintVars(timeOfLastNewValue)` and calculate it at submission time.

The reward calculation is currently done just once at the end of the challenge round (5th slot). This suggests doing it for that calculation on each nonce submission, which would increase gas further. Adding more data to the events also would increase gas. But really this is will create more data reads/writes and more calculations which means more gas used.

**Comment by themandalore** [comment]
Agreed with @mikeghen , I think it clutters events and can be calculated other ways

**Comment by krasi-georgiev** [comment]
Ok let's leave it out then. Thanks for the feedback.
