### ISSUE TITLE
Rename `timeOfLastNewValue` to `timeOfLastValue`

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#108]
I think the word `New` is redundant here and I was confused at first sight what it means. 
When replaced should revisit and replace in all Tellor projects that use it.

**Comment by themandalore** [comment]
can't do this because of the upgrade

**Comment by krasi-georgiev** [comment]
Just to add a bit more context for the future "ME" - this messes up accessing the variable from storage after the upgrade - the new contract will try to access a non-existing variable and it will opcode errors. so this is not worth the effort, but keeping it open as a reminder if we decide to fork and think how to improve this with upgrades - see if we can design it in a way to be able to rename vars without complications.
