### ISSUE TITLE
expose `currenReward` calculations as a function.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#109]
Also at the moment the `currenReward` logic is duplicated in the `miner` and in the `lens` projects. If the function is exposed it will remove the need for this code duplication.

**Comment by themandalore** [comment]
I'd actually say Nay on this one.  Thoughts @JGcarv ?  I think keeping the getters outside(as much as possible) is usually best practice

**Comment by krasi-georgiev** [comment]
But this is not actually a getter, but some logic to calculate the reward. If we don't expose it upgrading the contract means upgrading Lens, and the Miner, Otherwise they can just use the exposed function.
