### ISSUE TITLE
Duplicate var assignment in `_submitMiningSolution`

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#110]
_tblock.minersByValue[1][_slotProgress]= msg.sender;

https://github.com/tellor-io/TellorCore/blob/master/contracts/libraries/TellorLibrary.sol#L204
and 
https://github.com/tellor-io/TellorCore/blob/master/contracts/libraries/TellorLibrary.sol#L207

**Comment by themandalore** [comment]
yup, remove LN 204
