### ISSUE TITLE
Rename or describe better the `requestCount` variable

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#111]
This variable tracks the total number of added tips. In practice it is indeed a total number of requested values, but I think some better name or adding a better description should be added to avoid confustion.

**Comment by themandalore** [comment]
messes with the upgrade pieces

**Comment by krasi-georgiev** [comment]
Yep. In that let's add some commenting in the actual contract to describe the variable a bit better

This comment explains why we can't rename it
https://github.com/tellor-io/TellorCore/issues/108#issuecomment-736612864
