### ISSUE TITLE
Remove unused  uint storage variable.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#112]
Did a global search and don't think these are used anywhere

`runningTips`
`devShare`
`miningReward`
`currentReward`

**Comment by themandalore** [comment]
where do you see these?  Most of these are uintVar() which is a mapping no?

**Comment by krasi-georgiev** [comment]
Yeah some are not variables but just the keccak has like this one
https://github.com/tellor-io/TellorCore/blob/b110fcb0a06a0933f16b3b4f1bc478930dceb519/contracts/libraries/TellorLibrary.sol#L26

**Comment by themandalore** [comment]
ok, got it, these you can remove

**Comment by JGcarv** [comment]
Hmmm I guess they don't make any difference. Those are const declarations, which do not use storage, the are just discarded at compile time.

While they do take some space and leave the code messier, I think there's an argument to leave them there as a reminder that at some point those storage location were used.

**Comment by krasi-georgiev** [comment]
Can we comment them out with some more detailed explanation that these are legacy vars?
