### ISSUE TITLE
'currentRequestId' is not set anywhere but used in `getCurrentVariables` - check if it can be removed.

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#113]
Check if  `func getCurrentVariables` can be removed or overloaded as at the moment it uses `currentRequestId` which is not changed anywhere in the code.

**Comment by themandalore** [comment]
so this is in TellorMaster, you won't be able to change it until we fork

**Comment by krasi-georgiev** [comment]
Can we change this function to always throw an exception?
https://github.com/tellor-io/TellorCore/blob/f97773dc82e26c85bc5f22ff44ea70bf3ae93094/contracts/libraries/TellorGettersLibrary.sol#L129-L142
