### ISSUE TITLE
`NewValue` event returns the same value for all data IDs

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#129]
The `a` variable should record all 5 values and emits thise in the event. At the moment the event is emitted with the same value for all 5 data IDs.

https://github.com/tellor-io/TellorCore/blob/master/contracts/libraries/TellorLibrary.sol#L116-L122

**Comment by krasi-georgiev** [comment]
has it been fixed?

**Comment by krasi-georgiev** [comment]
yep I double-checked, this is fixed in the new contract

**Comment by themandalore** [comment]
sorry, forgot to add a comment!  But you got it!
