### ISSUE TITLE
timestamp not set for proposeFork in self.disputesById

### ISSUE THREAD

**Issue by krasi-georgiev** [tellor-io/TellorCore#131]
this is needed to show in the dispute center whether the vote is still in the voting window

**Comment by themandalore** [comment]
you can use the min_execution_date for this (it's just the block.timestamp + 7 days).  the timestamp normally refers to the timestamp up for dispute, so we wouldn't want to use this one either way (the vote is open longer)

**Comment by krasi-georgiev** [comment]
But if it set for the disputes why not also set it for the propose fork?

I can't remember the exact details, but IIRC this would make the tellorscan implementation a lot easyer
