### ISSUE TITLE
Improve error string for incorrect PoW solution

### ISSUE THREAD

**Issue by lodainn** [tellor-io/TellorCore#62]
The current error string "Challenge information is not saved" is unclear.  
Suggest something like: "Invalid solution"

**Comment by milkyklim** [comment]
Error coming from: https://github.com/tellor-io/TellorCore/blob/23098d4cc0c717d9d121e26d24e0723db4914f34/contracts/libraries/TellorLibrary.sol#L286 
Mike proposed: "Incorrect nonce for current challenge".
