### ISSUE TITLE
Fix getMax comment

### ISSUE THREAD

**Issue by themandalore** [tellor-io/TellorCore#68]
Add explainer for why skipping 0 too:  

The zero position here is ignored.  It's because there's no null in solidity and we map each address to an index in this array.  So when we get 51 parties, and one person is kicked out of the top 50, we assign them a 0, and when you get mined and pulled out of the top 50, also a 0.  So then lot's of parties will have zero as the index so we made the array run from 1-51 with zero as nothing.

**Comment by brendaloya** [comment]
Utilities.sol. Lines 9-16 added to explain why 0 position is skipped.
