### ISSUE TITLE
Lookup Timestamps by Request ID & Challenge Hash

### ISSUE THREAD

**Issue by mdcoon** [tellor-io/TellorCore#8]
Need a way to find all mined timestamps by challenge hash and request ID.

**Comment by themandalore** [comment]
does this work:
getNewValueCountbyRequestId(_requestId) - number of new Values
getTimestampbyRequestIDandIndex(_requestId,_index) - then you can loop through these timestamps

But for challengeHash, we do not save timestamps by nonceSubmission, just for newValues
