### ISSUE TITLE
Fix isInDispute function for any miner, not just median

### ISSUE THREAD

**Issue by mdcoon** [tellor-io/TellorCore#9]
Current implementation only checks whether the median miner was set whether there is an active dispute. But now we're disputing any submitted value. Need to either change this method to determine if any miner is in dispute for a previously submitted nonce/value or create a new function that offers this info.

**Comment by mdcoon** [comment]
Ideally, if I can lookup winning miners by requestId + challengeHash that would be good. If I can lookup disputes by the same plus miner index, that would be ideal

**Comment by themandalore** [comment]
We can look up disputeHash and return DisputeID: getDisputeIdByDisputeHash()
dispute hash = keccak256(abi.encodePacked(_miner,_requestId,_NewValueTimestamp))
If there  is a disputeID and it's within the 1 day challenge period, then it is in dispute
